{% set name = "green" %}
{% set version = "3.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8865d0b77b5cb13851dd601a58ad2c82bcb52da7ca106f0538c5787f127368a6

build:
  number: 0
  entry_points:
    - green = green.cmdline:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - colorama
    - python-termstyle
    - unidecode
    - mock
    - coverage
    - lxml

test:
  imports:
    - green
  commands:
    - green -h

about:
  home: https://github.com/CleanCut/green
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Green is a clean, colorful, fast python test runner
  description: >
    Green - A clean, colorful, fast python test runner.

    Features --------

    - **Clean** - Low redundancy in output. Result statistics for each test is vertically aligned. - **Colorful** - Terminal output makes good use of color when the terminal supports it. - **Fast** - Tests run in independent processes.  (One per processor by default.  Does *not* play nicely with `gevent`) - **Powerful**
    - Multi-target + auto-discovery. - **Traditional** - Use the normal `unittest` classes and methods for your unit tests. - **Descriptive** - Multiple verbosity levels, from just dots to full docstring output. - **Convenient** - Bash-completion and ZSH-completion of options and test targets. - **Thorough** - Built-in,
    optional integration with
      [coverage](http://nedbatchelder.com/code/coverage/).
    - **Embedded** - Can be run with a setup command without in-site installation. - **Modern** - Supports Python 2.7, and 3.4+. Additionally, [PyPy](http://pypy.org) is supported on a best-effort basis. - **Portable** - macOS, Linux, and BSDs are fully supported.  Windows is supported on a best-effort basis. - **Living**
    - This project grows and changes.  See the
  doc_url: https://github.com/CleanCut/green#green
  dev_url: https://github.com/CleanCut/green

extra:
  recipe-maintainers:
    - ReimarBauer
