travis:
  secure:
    BINSTAR_TOKEN: VGAWqpwf8dT6AvkBlMrbwiRzx6WpkHwHr7E3zDmC8TgRMjldlXVxDfLd9wdYqeyWt9adS7Q5x0Wnj6fahYaDiFIZaxRvpfk2O+AWkx59TZY6laFXJESb1N/RWM8uJAMg3P/M1JCAh2KHO/7lrNZf9S/50SIKwPKKvXYvG37IHsjZGylo5jnnVGwZpb7Qsa8d1Mra+a1hhOJPsNBdU9lC6YCdmvjm5bb8FfTX9fJW5EJCBMOfrfN7Cv3iijtf1jHVw6Zd2gvqSjBrNpFytqtKJNLxSY5jKrkpL6Qu3eGWjWQhjjWCjavteNeyY0p++J48c+HGI7l3gzSUuf56bRGFQM9gFmqDvT2dC+CQiIkDL/hbzOivkGpTV7lnPw8XvvYhBS7A4sRJtMdRV/N2O7BX4UlkrNN73j03VcB9Q4mrUWUorikHwdKJwwrMu6pFyVe/YYzx7hbaoHNvDxRe1Q75fjKuAlR1ffmtP5PDaAC48+OlVD9a1Z5fxmmTF9WfMhrMSfAlK9GJdznZwONqfsXNOBwfio1l8gsuxo9wfc9GrWYlYTM5DNHOmXApuf7bK4LPfROgeKBlgjfqhXjZAmn636aNd47AaBqR84+kVgbPXWxwFya2Xqtf7+KdgeprL6xue3+tvZ1wRT2JCU6UGk1BdhM3WhJuthvBjYHunfu7dXM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
